module.exports = {
	"Vista": {
		"Icono": "0",
		"Clave": "CuotasCobMenRVVIS",
		"Nombre": "CuotasCobMenRVVIS",
		"Modulos": ["(Todos)"],
		"Singular": "CuotasCobMenRVVIS",
		"ListaRelaciones": [
			"CuotasCobMenRangoTBL.RTipoComisionMavi",
			"CuotasCobMenRangoTBL.RvAgenteTipo",
			"CuotasCobMenRangoTBL.RvNivelCobranza",
			"CuotasCobMenRangoTBL.RTipoCuotaMavi",
			"CuotasCobMenRangoTBL.RLocalidad",
			"CuotasCobMenRangoTBL.RCuotasCobMenValor",
			"CuotasCobMenValorTBL.RCuotasCobMenRango",
		],
		"VistaIndependiente": "S",
		"ListaCampos": [
			"ID",
			"TipoComision",
			"TipoAgente",
			"NivelCobranza",
			"TipoCuota",
			"Localidad",
			"IN_RangoInicial",
			"IN_RangoFinal",
			"DV_Inicial",
			"DV_Final",
			"Requerido",
			"SaldoMinimo",
			"Cuota_Fija",
			"Cuota_Porcentaje",
			"PremioDeduccion",
			"Activa",
			"CUOTA_PORC_CAPITAL",
			"CAPITAL_PROMEDIO",
			"DV_PROMEDIO",
			"DI_PROMEDIO",
			"DIAS_REGULARIZACION",
			"RangoInicial",
			"RangoFinal",
			"PremioDeduccionV",
			"Apoyo",
			"TipoComisionMavi",
			"Tipo",
			"Nombre",
			"TipoCuotaMavi",
			"Opcion",
		],
		"SQL": [
			"SELECT *",
			"FROM V_DM0500BConsultaCuotas",
			"WHERE V_DM0500BConsultaCuotas.TipoComision LIKE <T>{Mavi.DM0500BTipoComisionTMP}<T>",
			"AND V_DM0500BConsultaCuotas.TipoAgente LIKE <T>{Mavi.DM0500BTipoAgenteTMP}<T>",
			"AND V_DM0500BConsultaCuotas.NivelCobranza LIKE <T>{Mavi.DM0500BNivelCobranzaTMP}<T>",
			"AND V_DM0500BConsultaCuotas.TipoCuota LIKE <T>{Mavi.DM0500BTipoCuotaTMP}<T>",
			"AND V_DM0500BConsultaCuotas.Localidad LIKE <T>{Mavi.DM0500BLocalidadTMP}<T>",
			"AND CASE WHEN <T>{Mavi.DM0500BActivaTMP}<T>=<T>%<T> THEN 2 ELSE V_DM0500BConsultaCuotas.Activa END LIKE CASE WHEN <T>{Mavi.DM0500BActivaTMP}<T>=<T>No<T> THEN 0 ELSE CASE WHEN <T>{Mavi.DM0500BActivaTMP}<T>=<T>SI<T> THEN 1 ELSE 2 END END"
		]
	},
	"Relaciones.CuotasCobMenRangoTBL.RTipoComisionMavi": {
		"Clave": "CuotasCobMenRangoTBL.RTipoComisionMavi",
		"TablaRemota": "TipoComisionMavi",
		"LlaveLocal": "CuotasCobMenRangoTBL.TipoComision",
		"LlaveRemota": "TipoComisionMavi",
		"TipoRelacion": "Forzosa"
	},
	"Relaciones.CuotasCobMenRangoTBL.RvAgenteTipo": {
		"Clave": "CuotasCobMenRangoTBL.RvAgenteTipo",
		"TablaRemota": "vAgenteTipo",
		"LlaveLocal": "CuotasCobMenRangoTBL.TipoAgente",
		"LlaveRemota": "Tipo",
		"TipoRelacion": "Forzosa"
	},
	"Relaciones.CuotasCobMenRangoTBL.RvNivelCobranza": {
		"Clave": "CuotasCobMenRangoTBL.RvNivelCobranza",
		"TablaRemota": "vNivelCobranzaMavi",
		"LlaveLocal": "CuotasCobMenRangoTBL.NivelCobranza",
		"LlaveRemota": "Nombre",
		"TipoRelacion": "Forzosa"
	},
	"Relaciones.CuotasCobMenRangoTBL.RTipoCuotaMavi": {
		"Clave": "CuotasCobMenRangoTBL.RTipoCuotaMavi",
		"TablaRemota": "TipoCuotaMavi",
		"LlaveLocal": "CuotasCobMenRangoTBL.TipoCuota",
		"LlaveRemota": "TipoCuotaMavi",
		"TipoRelacion": "Forzosa"
	},
	"Relaciones.CuotasCobMenRangoTBL.RLocalidad": {
		"Clave": "CuotasCobMenRangoTBL.RLocalidad",
		"TablaRemota": "vLocalidadAgenteMaviTBL",
		"LlaveLocal": "CuotasCobMenRangoTBL.Localidad",
		"LlaveRemota": "Opcion",
		"TipoRelacion": "Forzosa"
	},
	"Relaciones.CuotasCobMenRangoTBL.RCuotasCobMenValor": {
		"Clave": "CuotasCobMenRangoTBL.RCuotasCobMenValor",
		"TablaRemota": "CuotasCobMenValorTBL",
		"LlaveLocal": "CuotasCobMenRangoTBL.ID",
		"LlaveRemota": "ID",
		"TipoRelacion": "Opcional"
	},
	"Relaciones.CuotasCobMenValorTBL.RCuotasCobMenRango": {
		"Clave": "CuotasCobMenValorTBL.RCuotasCobMenRango",
		"TablaRemota": "CuotasCobMenRangoTBL",
		"LlaveLocal": "CuotasCobMenValorTBL.ID",
		"LlaveRemota": "ID",
		"TipoRelacion": "Forzosa"
	},
	"ID": {
		"Clave": "ID",
		"Nombre": "ID",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "10",
		"TipoDatos": "Numérico",
		"ClaveBDE": "ID"
	},
	"TipoComision": {
		"Clave": "TipoComision",
		"Nombre": "TipoComision",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "50",
		"TipoDatos": "Texto",
		"Tamano": "50",
		"ClaveBDE": "TipoComision"
	},
	"NivelCobranza": {
		"Clave": "NivelCobranza",
		"Nombre": "NivelCobranza",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "50",
		"TipoDatos": "Texto",
		"Tamano": "50",
		"ClaveBDE": "NivelCobranza"
	},
	"TipoCuota": {
		"Clave": "TipoCuota",
		"Nombre": "TipoCuota",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "50",
		"TipoDatos": "Texto",
		"Tamano": "50",
		"ClaveBDE": "TipoCuota"
	},
	"Localidad": {
		"Clave": "Localidad",
		"Nombre": "Localidad",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "255",
		"TipoDatos": "Texto",
		"Tamano": "255",
		"ClaveBDE": "Localidad"
	},
	"IN_RangoInicial": {
		"Clave": "IN_RangoInicial",
		"Nombre": "IN_RangoInicial",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "10",
		"TipoDatos": "NumFlotante",
		"ClaveBDE": "IN_RangoInicial"
	},
	"IN_RangoFinal": {
		"Clave": "IN_RangoFinal",
		"Nombre": "IN_RangoFinal",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "10",
		"TipoDatos": "NumFlotante",
		"ClaveBDE": "IN_RangoFinal"
	},
	"DV_Inicial": {
		"Clave": "DV_Inicial",
		"Nombre": "DV_Inicial",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "10",
		"TipoDatos": "Numérico",
		"ClaveBDE": "DV_Inicial"
	},
	"DV_Final": {
		"Clave": "DV_Final",
		"Nombre": "DV_Final",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "10",
		"TipoDatos": "Numérico",
		"ClaveBDE": "DV_Final"
	},
	"Requerido": {
		"Clave": "Requerido",
		"Nombre": "Requerido",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "10",
		"TipoDatos": "Numérico",
		"ClaveBDE": "Requerido"
	},
	"SaldoMinimo": {
		"Clave": "SaldoMinimo",
		"Nombre": "SaldoMinimo",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "10",
		"TipoDatos": "Numérico",
		"ClaveBDE": "SaldoMinimo"
	},
	"Cuota_Fija": {
		"Clave": "Cuota_Fija",
		"Nombre": "Cuota_Fija",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "10",
		"TipoDatos": "Numérico",
		"ClaveBDE": "Cuota_Fija"
	},
	"Cuota_Porcentaje": {
		"Clave": "Cuota_Porcentaje",
		"Nombre": "Cuota_Porcentaje",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "10",
		"TipoDatos": "Numérico",
		"ClaveBDE": "Cuota_Porcentaje"
	},
	"PremioDeduccion": {
		"Clave": "PremioDeduccion",
		"Nombre": "PremioDeduccion",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "10",
		"TipoDatos": "NumFlotante",
		"ClaveBDE": "PremioDeduccion"
	},
	"Activa": {
		"Clave": "Activa",
		"Nombre": "Activa",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "10",
		"TipoDatos": "Lógico",
		"ClaveBDE": "Activa"
	},
	"DV_PROMEDIO": {
		"Clave": "DV_PROMEDIO",
		"Nombre": "DV_PROMEDIO",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "10",
		"TipoDatos": "Lógico",
		"ClaveBDE": "DV_PROMEDIO"
	},
	"DI_PROMEDIO": {
		"Clave": "DI_PROMEDIO",
		"Nombre": "DI_PROMEDIO",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "10",
		"TipoDatos": "Lógico",
		"ClaveBDE": "DI_PROMEDIO"
	},
	"DIAS_REGULARIZACION": {
		"Clave": "DIAS_REGULARIZACION",
		"Nombre": "DIAS_REGULARIZACION",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "10",
		"TipoDatos": "Numérico",
		"ClaveBDE": "DIAS_REGULARIZACION"
	},
	"CUOTA_PORC_CAPITAL": {
		"Clave": "CUOTA_PORC_CAPITAL",
		"Nombre": "CUOTA_PORC_CAPITAL",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "10",
		"TipoDatos": "NumFlotante",
		"ClaveBDE": "CUOTA_PORC_CAPITAL"
	},
	"CAPITAL_PROMEDIO": {
		"Clave": "CAPITAL_PROMEDIO",
		"Nombre": "CAPITAL_PROMEDIO",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "10",
		"TipoDatos": "Lógico",
		"ClaveBDE": "CAPITAL_PROMEDIO"
	},
	"RangoInicial": {
		"Clave": "RangoInicial",
		"Nombre": "RangoInicial",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "10",
		"TipoDatos": "NumFlotante",
		"ClaveBDE": "RangoInicial"
	},
	"RangoFinal": {
		"Clave": "RangoFinal",
		"Nombre": "RangoFinal",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "10",
		"TipoDatos": "NumFlotante",
		"ClaveBDE": "RangoFinal"
	},
	"Apoyo": {
		"Clave": "Apoyo",
		"Nombre": "Apoyo",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "10",
		"TipoDatos": "Lógico",
		"ClaveBDE": "Apoyo"
	},
	"TipoAgente": {
		"Clave": "TipoAgente",
		"Nombre": "TipoAgente",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "50",
		"TipoDatos": "Texto",
		"Tamano": "50",
		"ClaveBDE": "TipoAgente"
	},
	"PremioDeduccionV": {
		"Clave": "PremioDeduccionV",
		"Nombre": "PremioDeduccionV",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "10",
		"TipoDatos": "NumFlotante",
		"ClaveBDE": "PremioDeduccionV"
	},
	"TipoComisionMavi": {
		"Clave": "TipoComisionMavi",
		"Nombre": "TipoComisionMavi",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "50",
		"TipoDatos": "Texto",
		"Tamano": "50",
		"ClaveBDE": "TipoComisionMavi"
	},
	"Tipo": {
		"Clave": "Tipo",
		"Nombre": "Tipo",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "20",
		"TipoDatos": "Texto",
		"Tamano": "20",
		"ClaveBDE": "Tipo"
	},
	"Nombre": {
		"Clave": "Nombre",
		"Nombre": "Nombre",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "100",
		"TipoDatos": "Texto",
		"Tamano": "100",
		"ClaveBDE": "Nombre"
	},
	"TipoCuotaMavi": {
		"Clave": "TipoCuotaMavi",
		"Nombre": "TipoCuotaMavi",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "50",
		"TipoDatos": "Texto",
		"Tamano": "50",
		"ClaveBDE": "TipoCuotaMavi"
	},
	"Opcion": {
		"Clave": "Opcion",
		"Nombre": "Opcion",
		"Visible": "S",
		"OpcionesColumnas": "1",
		"OpcionesRenglones": "8",
		"TamanoValidacion": "255",
		"TipoDatos": "Texto",
		"Tamano": "255",
		"ClaveBDE": "Opcion"
	}
}